
  - name: SSH | Install fail2ban
    apt: pkg=fail2ban state=present update-cache=yes
    become: yes
    tags:
      - ssh 

  - name: SSH | local fail2ban jail config
    template: src={{root_dir}}/files/security/jail.local.j2 dest=/etc/fail2ban/jail.local
    become: yes 
    tags:
      - ssh 

  - name: SSH |  reload fail2ban
    service: name=fail2ban state=reloaded      
    become: yes
    tags:
      - ssh 


