- name: Vagrant |Add HashiCorp GPG key
  ansible.builtin.shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true
  tags:
    - vagrant


- name: Vagrant | Add HashiCorp APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    filename: hashicorp
  become: true

- name: Vagrant | Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Vagrant | Install Vagrant
  ansible.builtin.apt:
    name: vagrant
    state: present
  become: true

- name: Vagrant | install plugins
  ansible.builtin.shell: "vagrant plugin install {{item}}"
  become: yes
  when: vagrant_plugins is defined
  with_items: "{{ vagrant_plugins | default(['vagrant-vbguest', 'hostupdater', 'vagrant-auto_network', 'vagrant-disksize', 'vagrant-hostmanager', 'vagrant-hostsupdater', 'vagrant-reload', 'vagrant-s3auth']) }}"
  tags:
    -vagrant
    -setup
