---
version: "3.7"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /home/slavko/apps/keyfiles/heimdall/config:/config
    ports:
      - 71:80
      - 7443:443
    networks:
        traefik-public:
    extra_hosts:
        docker.lvh.voronenko.net: 172.25.0.1
        lvh.voronenko.net: 172.25.0.1
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m
#      timeout: 10s
#      retries: 3
#      start_period: 20s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.heim.rule=Host(`lvh.voronenko.net`,`me.voronenko.net`)"
        - "traefik.http.routers.heim.entrypoints=web"
        - "traefik.http.services.heim.loadbalancer.server.port=80"

  #      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
  #      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
  #      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

        - "traefik.http.routers.heim-secure.entrypoints=websecure"
        - "traefik.http.routers.heim-secure.rule=Host(`lvh.voronenko.net`,`me.voronenko.net`)"
  #      - "traefik.http.routers.heim-secure.middlewares=traefik-auth"
        - "traefik.http.routers.heim-secure.tls=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heim.rule=Host(`lvh.voronenko.net`,`me.voronenko.net`)"
      - "traefik.http.routers.heim.entrypoints=web"
      - "traefik.http.services.heim.loadbalancer.server.port=80"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.heim-secure.entrypoints=websecure"
      - "traefik.http.routers.heim-secure.rule=Host(`lvh.voronenko.net`,`me.voronenko.net`)"
#      - "traefik.http.routers.heim-secure.middlewares=traefik-auth"
      - "traefik.http.routers.heim-secure.tls=true"
    restart: unless-stopped
networks:
  traefik-public:
    external: true

