---
  - name: AuditD | Install packages
    ansible.builtin.apt:
      pkg:
        - auditd
    become: true
    tags:
      - auditd

  - name: AuditD | Patch /etc/audit/auditd.conf
    ansible.builtin.lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
      insertafter: "{{item.insertafter | default('EOF')}}"
    with_items: "{{auditd_conf_default_props | default([])}}"
    become: true
    tags:
      - auditd

  - name: AuditD | Restart service
    ansible.builtin.service:
      name: auditd
      state: restarted
      enabled: yes
    when: docker_test is not defined
    become: true
    tags:
      - auditd
