#!/usr/bin/plantuml
@startuml
object default_parameters

default_parameters : mysql_root_user = "root"
default_parameters : id = 123
default_parameters : mysql_root_password = "devroot"
default_parameters : apache_mode = "worker"
default_parameters : java_version = "8"
default_parameters : phpstorm_version = "9.0.2"
default_parameters : pycharm_version = "4.5.4"
default_parameters : rubymine_version = "7.1.4"
default_parameters : intellij_version = "14.1.4"
default_parameters : robomongo_version = "0.8.5"
default_parameters : dbeawer_version = "3.4.5"
default_parameters : oracle_vbox_version = "4.3"
default_parameters : mongo_version = "3"
default_parameters : vagrant_version = "1.7.4"
default_parameters : nodejs_version = "0.12"
default_parameters : php_family = "default"
default_parameters : hypervisor = "esx"


@enduml
